In [8]:
import geopandas as gpd
import glob
import pandas as pd

files = glob.glob("/Users/morrylk/Cours_M1_Ynov/Machine-Learning/Sujet Projet (partie 1 et 2)-20260504/departements-france-polygons/*.json")

gdfs = [gpd.read_file(f) for f in files]

In [9]:
if gdfs:
    gdf = gpd.GeoDataFrame(pd.concat(gdfs, ignore_index=True))
    display(gdf.head())
else:
    print("No GeoDataFrames found. Please check the input directory for JSON files.")

,Country/Region,Province/State,Code,Population,Beds,Deaths,Recovered,Severe,Critical,Emergencies,MedicalActs,MedicalTests,Confirmed,geometry,PCRTests
0,France,Guadeloupe,971,"{ ""Total"": 376879, ""Under19"": 90617, ""Under39""...","{ ""Resuscitation"": 27, ""IntensiveCare"": 68, ""T...",14.0,72.0,21.0,10.0,"{ ""Suspected"": 7, ""Total"": 169, ""Severe"": 1, ""...",None,"{ ""Total"": 1, ""Confirmed"": 1, ""Total\/Accumula...",106.0,"MULTIPOLYGON (((-61.63356 15.83977, -61.6505 1...",NaN
1,France,Martinique,972,"{ ""Total"": 358749, ""Under19"": 77005, ""Under39""...","{ ""Resuscitation"": 26, ""IntensiveCare"": 58, ""T...",14.0,64.0,32.0,8.0,None,"{ ""Total"": 82, ""Suspected\/Accumulated"": 118, ...","{ ""Total\/Accumulated"": 24, ""Confirmed\/Accumu...",16.0,"POLYGON ((-61.11754 14.62759, -61.13591 14.634...",NaN
2,France,Guyane,973,"{ ""Total"": 290691, ""Under19"": 120681, ""Under39...","{ ""Resuscitation"": 13, ""IntensiveCare"": 12, ""T...",1.0,35.0,1.0,NaN,"{ ""Suspected"": 1, ""Total"": 129, ""Severe"": 1, ""...",None,"{ ""Total\/Accumulated"": 31, ""Confirmed\/Accumu...",43.0,"POLYGON ((-53.46939 5.56526, -53.4564 5.56863,...",NaN
3,France,Mayotte,976,"{ ""Total"": 279471, ""Under19"": 150257, ""Under39...","{ ""Resuscitation"": 6, ""IntensiveCare"": 0, ""Tot...",6.0,79.0,35.0,5.0,"{ ""Suspected"": 36, ""Total"": 121, ""Severe"": 4, ...",None,"{ ""Total\/Accumulated"": 2, ""Confirmed\/Accumul...",128.0,"MULTIPOLYGON (((45.04101 -12.64686, 45.03308 -...",NaN
4,France,Ain,01,"{ ""Total"": 656955, ""Under19"": 167666, ""Under39...","{ ""Resuscitation"": 22, ""IntensiveCare"": 20, ""T...",79.0,251.0,161.0,15.0,"{ ""Suspected"": 8, ""Total"": 143, ""Severe"": 5, ""...",None,"{ ""Total"": 57, ""Confirmed"": 2, ""Total\/Accumul...",118.0,"POLYGON ((4.78021 46.17668, 4.78024 46.18905, ...",NaN

In [ ]:
gdf.isna().sum()
#

Country/Region        0
Province/State        0
Code                  0
Population            0
Beds                  0
Deaths             1982
Recovered          1840
Severe             2479
Critical           6307
Emergencies         373
MedicalActs       20515
MedicalTests       2086
Confirmed          3171
geometry              0
PCRTests           7373
dtype: int64

In [12]:
gdf.shape

(37673, 15)

In [11]:
gdf.describe()

             Deaths     Recovered        Severe      Critical     Confirmed
count  35691.000000  35833.000000  35194.000000  31366.000000  34502.000000
mean     275.130229   1152.445037    178.371200     27.162851    112.702510
std      411.376658   1778.865211    270.812369     48.549538    148.815054
min        1.000000      1.000000      1.000000      1.000000      1.000000
25%       40.000000    175.000000     22.000000      4.000000     22.000000
50%      110.000000    504.000000     78.000000     10.000000     55.000000
75%      307.000000   1243.000000    214.000000     29.000000    128.000000
max     3321.000000  15163.000000   3281.000000    855.000000    827.000000

In [15]:
gdf.isna().mean() * 100

Country/Region     0.000000
Province/State     0.000000
Code               0.000000
Population         0.000000
Beds               0.000000
Deaths             5.261062
Recovered          4.884135
Severe             6.580310
Critical          16.741433
Emergencies        0.990099
MedicalActs       54.455446
MedicalTests       5.537122
Confirmed          8.417169
geometry           0.000000
PCRTests          19.571046
dtype: float64